config/routes.rb
TrackUser::Application.routes.draw do
  
  resources :locations
  get "dashboard/dashboard"

  devise_for :users

  get "home/index"
  get "home/download_file"

   root :to => 'home#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :city, :country_code, :country_name, :ip, :latitude, :longitude, :metrocode, :region_code, :region_name, :zipcode
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_type
  # attr_accessible :title, :body

  USER_TYPES = [["Admin", 1], ["User", 2]]

  def is_admin?
  	self.user_type == 1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def check_admin_logged_in!
  	if current_user and current_user.is_admin?
  		true
  	else
  		false
  	end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def download_file
  	Location.create(city: request.location.city, country_code: request.location.country_code,
  	 ip: request.remote_ip, latitude: request.location.latitude, longitude: request.location.longitude, 
  	 metrocode: request.location.metrocode)
  	send_file "app/assets/images/rails.png"
  end 	
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin_logged_in!
  def index
  	if params[:search].present?
	 @locations = Location.near(params[:search], 50, :order => :distance)
	else
	 @locations = Location.all
	end
  end

  def show
  	@location = Location.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/dashboard/dashboard.html.erb
<h1>Dashboard#dashboard</h1>
<p>Find me in app/views/dashboard/dashboard.html.erb</p>

app/views/home/index.html.erb
<%= link_to "Download app", home_download_file_path() %>

app/views/layouts/_header_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if current_user %>
			<li><%= link_to "Dashboard", dashboard_dashboard_path  %></li>
			<li><%= link_to "Locations", locations_path %></li>
			<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "Sign up", new_user_registration_path %></li>
			<li><%= link_to "Sign in", new_user_session_path %></li>
		<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TrackUser</title>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Bootstrap -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render "/layouts/header_navigation" %>
	<div class="container">
	<%= yield %>
	</div>
</body>
</html>

app/views/locations/index.html.erb
<%= form_tag locations_path, :class => "form-inline", :method => :get do %>
  <div class="form-group">
    <label class="sr-only" for="exampleInputEmail3">Email address</label>
    <%= text_field_tag :search, params[:search], :class => "form-control" %>
  </div>
  <%= submit_tag "Search Near", :name => nil, :class => "btn btn-default" %>
<% end %>
<br/>

<div class="table-responsive">
	<table class="table table-hover">
	<tr>
		<td>Id</td>
		<td>Address</td>
		<td>Latitude</td>
		<td>Longitude</td>
	</tr>
	<% @locations.each do |location| %>
	 <tr>
	 	<td><%= link_to location.id, location_path(location) %></td>
	 	<td><%= location.address %></td>
	 	<td><%= location.latitude %></td>
	 	<td><%= location.longitude %></td>
	 </tr>
	<% end %>
	</table>
</div>

app/views/locations/show.html.erb
<dl class="dl-horizontal">
  <dt><strong>Address:</strong></dt>
  <dd><%= @location.address %></dd>

  <dt><strong>Latitude:</strong></dt>
  <dd><%= @location.latitude %></dd>

  <dt><strong>Longitude:</strong></dt>
  <dd><%= @location.longitude %></dd>
 </dl>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>